# Generated by Django 3.2.5 on 2021-07-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_billingprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='activa',
            new_name='active',
        ),
    ]
