# Generated by Django 3.2.5 on 2021-08-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Card',
        ),
    ]
