# Generated by Django 3.2.5 on 2021-07-31 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectviewed',
            old_name='User',
            new_name='user',
        ),
    ]
